# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simpsonC <- function(x, fx) {
    .Call('DstarM_simpsonC', PACKAGE = 'DstarM', x, fx)
}

dunifc <- function(x, a, b) {
    .Call('DstarM_dunifc', PACKAGE = 'DstarM', x, a, b)
}

convolveC <- function(x, y) {
    .Call('DstarM_convolveC', PACKAGE = 'DstarM', x, y)
}

convolveC2 <- function(x, y) {
    .Call('DstarM_convolveC2', PACKAGE = 'DstarM', x, y)
}

chisqC <- function(tt, a, b) {
    .Call('DstarM_chisqC', PACKAGE = 'DstarM', tt, a, b)
}

rObjC3 <- function(r, tt, a, bb, lenPre, lenPost) {
    .Call('DstarM_rObjC3', PACKAGE = 'DstarM', r, tt, a, bb, lenPre, lenPost)
}

rObjC2 <- function(r, tt, a, bb, lenPre) {
    .Call('DstarM_rObjC2', PACKAGE = 'DstarM', r, tt, a, bb, lenPre)
}

rObjC1 <- function(r, tt, a, bb, lenPost) {
    .Call('DstarM_rObjC1', PACKAGE = 'DstarM', r, tt, a, bb, lenPost)
}

rObjC0 <- function(r, tt, a, bb) {
    .Call('DstarM_rObjC0', PACKAGE = 'DstarM', r, tt, a, bb)
}

nthMomentSC <- function(x, fx, nth) {
    .Call('DstarM_nthMomentSC', PACKAGE = 'DstarM', x, fx, nth)
}

nthCMomentSC <- function(x, fx, nth) {
    .Call('DstarM_nthCMomentSC', PACKAGE = 'DstarM', x, fx, nth)
}

getVarC <- function(Pdf, tt, mm2) {
    .Call('DstarM_getVarC', PACKAGE = 'DstarM', Pdf, tt, mm2)
}

oscCheckC <- function(x) {
    .Call('DstarM_oscCheckC', PACKAGE = 'DstarM', x)
}

getVoss <- function(rt, pars, precision) {
    .Call('DstarM_getVoss', PACKAGE = 'DstarM', rt, pars, precision)
}

imposeFixationsC <- function(pars, fixed) {
    .Call('DstarM_imposeFixationsC', PACKAGE = 'DstarM', pars, fixed)
}

getPdfC <- function(tt, pars, mm, DstarM, oscPdf, precision) {
    .Call('DstarM_getPdfC', PACKAGE = 'DstarM', tt, pars, mm, DstarM, oscPdf, precision)
}

totalobjectiveC <- function(pars, tt, ql, ii, jj, varData, g, restr, mm, mm2, DstarM, oscPdf, forceRestriction, precision, anyFixed, fixed) {
    .Call('DstarM_totalobjectiveC', PACKAGE = 'DstarM', pars, tt, ql, ii, jj, varData, g, restr, mm, mm2, DstarM, oscPdf, forceRestriction, precision, anyFixed, fixed)
}

